// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:carte/config/hive/hive_adapters.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(HiveCommentAdapter());
    registerAdapter(HiveOrderAdapter());
    registerAdapter(HiveProductAdapter());
    registerAdapter(HiveUserAdapter());
    registerAdapter(UuidV4Adapter());
  }
}
